import {
  faCalendarDays, faChevronLeft, faChevronRight, faCircleInfo, faClockRotateLeft, faFlask, faGear, faHeartPulse,
  faHouse, faMagnifyingGlass, faMars, faMoon, faPills, faRulerVertical, faSquare, faSquareCheck, faStar, faSun,
  faTrashCan, faTriangleExclamation, faChild, faMicroscope, faEnvelope, faLock, faUser, faUserInjured, faVenus, faVial, faWeightScale, faBars,
  type IconDefinition,
} from '@fortawesome/free-solid-svg-icons';

// Nomes iguais aos usados no app original (FontAwesome5) → ícones equivalentes do FontAwesome atual.
export const ICONES: Record<string, IconDefinition> = {
  'calendar-alt': faCalendarDays,
  'check-square': faSquareCheck,
  'chevron-left': faChevronLeft,
  'chevron-right': faChevronRight,
  'exclamation-triangle': faTriangleExclamation,
  'info-circle': faCircleInfo,
  'ruler-vertical': faRulerVertical,
  'trash-alt': faTrashCan,
  'user-injured': faUserInjured,
  heartbeat: faHeartPulse,
  history: faClockRotateLeft,
  weight: faWeightScale,
  search: faMagnifyingGlass,
  cog: faGear,
  home: faHouse,
  bars: faBars,
  envelope: faEnvelope,
  lock: faLock,
  user: faUser,
  child: faChild,
  microscope: faMicroscope,
  flask: faFlask,
  mars: faMars,
  moon: faMoon,
  pills: faPills,
  square: faSquare,
  star: faStar,
  sun: faSun,
  venus: faVenus,
  vial: faVial,
};
